blank_issues_enabled: true
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/freedomofpress/dangerzone?tab=security-ov-file
    about: Please report security vulnerabilities here.
